### ISSUE TITLE
Standardize search boxes with fuzzy string match/auto-complete

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-fhir-data-dashboard#70]
Could all of our search boxes make use of fuzzy string matching (or maybe called auto-complete?)? 

I noticed that this feature exists when searching the resource types but not when searching the StructureDefinitions by id. In the latter case, you have to type in the exact string to find the resource.

**Comment by abgeorge7** [comment]
@znatty22 right now that's because it would slow down the frontend to preload tens of thousands of IDs - the table is loaded as the page scrolls, so the search bar doesn't know all the IDs up front. If this is something that we want to change we can, it just will probably be a lot slower on initial load

**Comment by znatty22** [comment]
Hmm ok, maybe we don't need auto-complete on all of the search boxes but it would be really useful for the StructureDefinition one. Is that possible?
